name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust this as necessary for your workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@ec2-13-201-186-54.ap-south-1.compute.amazonaws.com:/home/ubuntu/social
          # You can also use scp if preferred:
          # scp -r -o StrictHostKeyChecking=no ./ ubuntu@ec2-13-201-186-54.ap-south-1.compute.amazonaws.com:/home/ubuntu/social
